### ISSUE TITLE
About the new TeXLive packages

### ISSUE THREAD

**Issue by angelog0** [msys2/msys2-texlive#8]
Usually I install TeXLive on GNU/Linux, macOS, WSL[2] and Termux using the `install-tl script` (choosing `/opt/texlive` as installation directory, and all components...).

Can I install your product that way? How?

**Comment by naveen521kk** [comment]
This repository is all about packaging TexLive for MSYS2, see https://packages.msys2.org/base/mingw-w64-texlive-core
If you have installed [MSYS2](https://msys2.org), it's about running
for x86_64 system,
```sh
pacman -S mingw-w64-x86_64-texlive-core
```
for i686 system,
```
pacman -S mingw-w64-i686-texlive-core
```
You would get `scheme-medium` type install with that method. Other packages are still a WIP.

**Comment by angelog0** [comment]
I understand all this (in the past have built TeXLive on different systems) but asked something different: if one can install a _standalone_ full distribution of TexLive with the `install-tl` script (see [this](https://www.tug.org/texlive/quickinstall.html)): I use it on GNU/Linux, macOS, WSL[2}, Termux (and Cygwin, when I used it). In principle one needs only the binaries (see [this](https://www.tug.org/texlive/custom-bin.html)) and some packages (`perl` etc.).

**Comment by angelog0** [comment]
On [Termux](https://termux.com), for example, one needs to install only two packages, `texlive-bin` and `texlive-installer`, the first contains the binaries and the second the adapted to Termux `install-tl` script (see [this](https://wiki.termux.com/wiki/TeX_Live#Details_on_how_texlive-installer_works)). On MINGW64/MSYS2, maybe, we need only the binaries. I wonder if the MSYS2 `perl` is enough without installing the `mingw-w64-perl`... It is for this reason I am asking to developers, and I am asking here because on MINGW-packages i didn't get answer.

**Comment by naveen521kk** [comment]
>  if one can install a standalone full distribution of TexLive with the install-tl script (see this): 

Yes, you can, but think of these packages as if it was for distros for example see how [arch's packages](https://archlinux.org/packages/?q=texlive) are, if you take termux it's like the `texlive-full` package they distribute.

> In principle one needs only the binaries (see this) and some packages (perl etc.).

For only binaries, there is [texlive-bin](https://packages.msys2.org/base/mingw-w64-texlive-bin) never tried it with `install-tl` script, you are on your own.

> I wonder if the MSYS2 perl is enough without installing the mingw-w64-perl... 

No, you would need `mingw-w64-perl`, because the MSYS2 Perl doesn't have access to Windows API's (afaik) which TexLive scripts needs.

> It is for this reason I am asking to developers

I still don't understand your question fully though, maybe elaborate on what you are trying to do?

**Comment by naveen521kk** [comment]
Closing because of no response.
